// Runs at commit time via .husky/pre-commit.
// ESLint --fix on the staged TS/TSX files; a full project typecheck (tsc reads
// the whole tsconfig, so it is not passed the staged file list).
// next-env.d.ts is auto-generated by Next.js and must never be linted, and the
// agent skills under .claude/skills are vendored third-party files — eslint
// warns "File ignored by default" when a path it ignores is passed explicitly,
// which fails the hook under --max-warnings=0.
const UNLINTABLE = [/next-env\.d\.ts$/, /(^|\/)\.claude\/skills\//, /(^|\/)\.agents\//];

export default {
  '*.{ts,tsx}': (stagedFiles) => {
    const lintable = stagedFiles.filter((f) => !UNLINTABLE.some((pattern) => pattern.test(f)));
    return [
      // Quoted: the paths are absolute, and a checkout under a folder with a
      // space in its name ("HoyosBaker Consulting LLC") split every one of them.
      ...(lintable.length
        ? [`eslint --fix --max-warnings=0 ${lintable.map((f) => JSON.stringify(f)).join(' ')}`]
        : []),
      'tsc --noEmit',
    ];
  },
};
