// Runs at commit time via .husky/pre-commit.
// ESLint --fix on the staged TS/TSX files; a full project typecheck (tsc reads
// the whole tsconfig, so it is not passed the staged file list).
// next-env.d.ts is auto-generated by Next.js and must never be linted.
export default {
  '*.{ts,tsx}': (stagedFiles) => {
    const lintable = stagedFiles.filter((f) => !f.endsWith('next-env.d.ts'));
    return [
      ...(lintable.length ? [`eslint --fix --max-warnings=0 ${lintable.join(' ')}`] : []),
      'tsc --noEmit',
    ];
  },
};
