// Regenerates .env.test.local from the running local Supabase stack.
//
// The test suites must never touch a real tenant: they create and delete users,
// businesses and storage objects with the service role. `.env.local` is the
// *app's* dev config and may legitimately point at the cloud project, so the
// suites read this file first (tests/setup/load-env.ts). It holds the demo keys
// every Supabase CLI installation ships with — nothing secret — plus a
// placeholder Anthropic key, since every suite mocks Anthropic at the HTTP layer.
import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';

const HEADER = `# Local Docker Supabase, for the test suites ONLY. Generated by \`pnpm env:test\`.
# Gitignored. See docs/ENVIRONMENTS.md → "Which file is which".
`;

function status(): Record<string, string> {
  const out = execFileSync('npx', ['supabase', 'status', '-o', 'env'], { encoding: 'utf8' });
  return Object.fromEntries(
    [...out.matchAll(/^([A-Z0-9_]+)="(.*)"$/gm)].map((match) => [match[1] as string, match[2] as string]),
  );
}

const env = status();
const required = ['API_URL', 'ANON_KEY', 'SERVICE_ROLE_KEY'] as const;
for (const key of required) {
  if (!env[key]) {
    console.error(`[env:test] ${key} missing — is local Supabase running? (pnpm supabase:start)`);
    process.exit(1);
  }
}

writeFileSync(
  '.env.test.local',
  `${HEADER}
NEXT_PUBLIC_APP_URL=http://localhost:3000
APP_URL=http://localhost:3000
NEXT_PUBLIC_SUPABASE_URL=${env.API_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${env.ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${env.SERVICE_ROLE_KEY}
CRON_SECRET=test-cron-secret-not-a-real-one

# Anthropic is mocked at the HTTP layer in every suite, so a placeholder is
# enough; a real key in the environment still wins (the opt-in live tests).
ANTHROPIC_API_KEY=sk-ant-test-not-a-real-key
ANTHROPIC_FAST_MODEL=fast-test-model
ANTHROPIC_REASONING_MODEL=reasoning-test-model
`,
);
console.log('[env:test] wrote .env.test.local from the local Supabase stack');
